# Pernambuco Spatial Model 1 -- Sections 17-18: state-level PPC figures and
# the homogeneous-vs-spatial comparison table.

required_packages <- c("rstan", "dplyr", "readr", "tibble", "ggplot2", "tidyr", "patchwork")
missing_packages <- required_packages[!vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_packages)) stop("Missing package(s): ", paste(missing_packages, collapse = ", "))
suppressPackageStartupMessages({ library(rstan); library(dplyr); library(readr); library(tibble); library(ggplot2); library(tidyr); library(patchwork) })

root <- "C:/Users/user/OneDrive - London School of Hygiene and Tropical Medicine/Documents/GitHub/CHIK_CLIM/CHIK_CLIM"
pe_root <- file.path(root, "02_Script/40_renewal_model/33_pernambuco_v4_9_replication")
table_dir <- file.path(root, "03_Output/tables/pernambuco_v4_9_replication/spatial_model")
figure_dir <- file.path(root, "03_Output/figures/pernambuco_v4_9_replication/spatial5")
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)
turnover_table_dir <- file.path(root, "03_Output/tables/pernambuco_v4_9_replication/spatial_turnover_diagnostic")

b <- readRDS(file.path(pe_root, "outputs/spatial5/pe_5strata_pilot.rds"))
fit <- b$fit
stratum_levels <- b$stratum_levels
R <- b$stan_data$R
draws <- rstan::extract(fit, permuted = TRUE)
weeks <- readRDS(file.path(turnover_table_dir, "pe_municipality_week_panel.rds")) |> pull(week_start) |> unique() |> sort()

theme_v4 <- theme_classic(base_size = 9) + theme(panel.grid.major.y = element_line(colour = "grey90"))
stratum_colours <- c("1_Recife" = "#D55E00", "2_Metropolitana_remainder" = "#E69F00",
                      "3_Agreste" = "#009E73", "4_Sertao" = "#0072B2", "5_Vale_Sao_Francisco_Araripe" = "#CC79A7")

summarise_draws <- function(arr2d) { # arr2d: [iter, N]
  tibble(median = apply(arr2d, 2, median), lo95 = apply(arr2d, 2, quantile, .025), hi95 = apply(arr2d, 2, quantile, .975))
}

# ---- Figure: regional observed vs predicted weekly cases + summed state ----
regional_ppc <- bind_rows(lapply(seq_len(R), function(r) {
  s <- summarise_draws(draws$C_pred[, , r])
  s$week_start <- weeks; s$observed <- b$stan_data$C[, r]; s$stratum <- stratum_levels[r]
  s
}))
p_regional_ppc <- ggplot(regional_ppc, aes(week_start)) +
  geom_ribbon(aes(ymin = lo95, ymax = hi95, fill = stratum), alpha = 0.25) +
  geom_line(aes(y = median, colour = stratum), linewidth = 0.3) +
  geom_point(aes(y = observed), colour = "black", size = 0.25, alpha = 0.5) +
  facet_wrap(~stratum, ncol = 1, scales = "free_y") +
  scale_colour_manual(values = stratum_colours, guide = "none") + scale_fill_manual(values = stratum_colours, guide = "none") +
  labs(title = "Pernambuco Spatial Model 1: regional observed vs predicted weekly cases",
       subtitle = "Black points = observed; ribbon = 95% posterior predictive", x = NULL, y = "Weekly cases") +
  theme_v4 + theme(strip.background = element_blank())
ggsave(file.path(figure_dir, "PE_5strata_case_PPC.png"), p_regional_ppc, width = 220, height = 260, units = "mm", dpi = 300, bg = "white")
message("[saved] ", file.path(figure_dir, "PE_5strata_case_PPC.png"))

# ---- State aggregate PPC (SUM of regional predictions, per Section 10/17) ----
state_pred_summary <- summarise_draws(draws$C_pred_state_sum)
state_pred_summary$week_start <- weeks
state_pred_summary$observed <- rowSums(b$stan_data$C)
p_state_ppc <- ggplot(state_pred_summary, aes(week_start)) +
  geom_ribbon(aes(ymin = lo95, ymax = hi95), fill = "#315A7D", alpha = 0.25) +
  geom_line(aes(y = median), colour = "#315A7D", linewidth = 0.4) +
  geom_point(aes(y = observed), colour = "black", size = 0.3, alpha = 0.5) +
  labs(title = "Pernambuco Spatial Model 1: statewide case PPC (SUM of 5 regional predictions)",
       subtitle = "Not separately fit to the state series (Section 10) -- generated by summing regional posterior predictions",
       x = NULL, y = "Weekly cases (state total)") +
  theme_v4
ggsave(file.path(figure_dir, "PE_spatial_state_aggregate_PPC.png"), p_state_ppc, width = 220, height = 130, units = "mm", dpi = 300, bg = "white")
message("[saved] ", file.path(figure_dir, "PE_spatial_state_aggregate_PPC.png"))

# ---- Regional susceptibility trajectories + statewide S_PE(t) -------------
S_traj <- bind_rows(lapply(seq_len(R), function(r) {
  s <- summarise_draws(draws$S_prop[, , r]); s$week_start <- weeks; s$stratum <- stratum_levels[r]; s
}))
p_S_regional <- ggplot(S_traj, aes(week_start, median, colour = stratum)) +
  geom_ribbon(aes(ymin = lo95, ymax = hi95, fill = stratum), alpha = 0.15, colour = NA) +
  geom_line(linewidth = 0.4) +
  scale_colour_manual(values = stratum_colours, name = NULL) + scale_fill_manual(values = stratum_colours, guide = "none") +
  labs(title = "Regional susceptible proportion S/N by stratum", x = NULL, y = "S / N") +
  theme_v4 + theme(legend.position = "top")

statewide_S <- summarise_draws(draws$S_PE_prop); statewide_S$week_start <- weeks
p_S_state <- ggplot(statewide_S, aes(week_start, median)) +
  geom_ribbon(aes(ymin = lo95, ymax = hi95), fill = "grey40", alpha = 0.2) +
  geom_line(colour = "grey20", linewidth = 0.5) +
  labs(title = "Statewide susceptible proportion S_PE(t) (GENERATED, not directly fitted)", x = NULL, y = "S_PE / N_PE") +
  theme_v4
ggsave(file.path(figure_dir, "PE_5strata_susceptibility.png"), p_S_regional / p_S_state, width = 220, height = 220, units = "mm", dpi = 300, bg = "white")
message("[saved] ", file.path(figure_dir, "PE_5strata_susceptibility.png"))

# ---- Regional R0 / Reff trajectories ---------------------------------------
R0_traj <- bind_rows(lapply(seq_len(R), function(r) {
  s <- summarise_draws(draws$R0_t[, , r]); s$week_start <- weeks; s$stratum <- stratum_levels[r]; s$quantity <- "R0"; s
}))
Reff_traj <- bind_rows(lapply(seq_len(R), function(r) {
  s <- summarise_draws(draws$R_eff_t[, , r]); s$week_start <- weeks; s$stratum <- stratum_levels[r]; s$quantity <- "Reff"; s
}))
p_R0 <- ggplot(R0_traj, aes(week_start, median, colour = stratum)) + geom_line(linewidth = 0.3) +
  scale_colour_manual(values = stratum_colours, name = NULL) +
  labs(title = "Regional R0(t)", x = NULL, y = "R0") + theme_v4 + theme(legend.position = "top")
p_Reff <- ggplot(Reff_traj, aes(week_start, median, colour = stratum)) + geom_line(linewidth = 0.3) +
  geom_hline(yintercept = 1, linetype = "dashed", colour = "grey50") +
  scale_colour_manual(values = stratum_colours, guide = "none") +
  labs(title = "Regional effective reproduction number Reff(t) = R0(t)*S/N", x = NULL, y = "Reff") + theme_v4
ggsave(file.path(figure_dir, "PE_5strata_R0_Reff.png"), p_R0 / p_Reff, width = 220, height = 200, units = "mm", dpi = 300, bg = "white")
message("[saved] ", file.path(figure_dir, "PE_5strata_R0_Reff.png"))

# ---- Recife U14 serology fit ------------------------------------------------
p_site <- draws$p_site_window[, 1]
obs_prev <- b$stan_data$sero_n_positive[1] / b$stan_data$sero_n_tested[1]
obs_ci <- prop.test(b$stan_data$sero_n_positive[1], b$stan_data$sero_n_tested[1])$conf.int
sero_df <- tibble(source = c("Model (Recife stratum, direct link)", "Observed (U14)"),
                   median = c(median(p_site), obs_prev), lo95 = c(quantile(p_site, .025), obs_ci[1]),
                   hi95 = c(quantile(p_site, .975), obs_ci[2]))
p_sero <- ggplot(sero_df, aes(source, median, colour = source)) +
  geom_point(size = 3) + geom_errorbar(aes(ymin = lo95, ymax = hi95), width = 0.15) +
  scale_colour_manual(values = c("Model (Recife stratum, direct link)" = "#D55E00", "Observed (U14)" = "black"), guide = "none") +
  labs(title = "Recife U14 serology: model (direct Recife-stratum link) vs observed",
       subtitle = "Spatial Model 1 uses NO geographic-offset transport (Section 9) -- Recife IS its own stratum",
       x = NULL, y = "Seroprevalence") + theme_v4 + coord_flip()
ggsave(file.path(figure_dir, "PE_Recife_U14_fit.png"), p_sero, width = 180, height = 90, units = "mm", dpi = 300, bg = "white")
message("[saved] ", file.path(figure_dir, "PE_Recife_U14_fit.png"))
message(sprintf("\nRecife U14 fit: model median=%.4f [%.4f,%.4f] vs observed=%.4f [%.4f,%.4f]",
                 median(p_site), quantile(p_site,.025), quantile(p_site,.975), obs_prev, obs_ci[1], obs_ci[2]))

# ---- Section 18: homogeneous vs spatial comparison table -------------------
homog <- readRDS(file.path(pe_root, "outputs/modelB_U14_full/renewal_pe_global_q_fit_modelB_U14_full.rds"))
homog_fit <- homog$fit
homog_draws <- rstan::extract(homog_fit, permuted = TRUE)
homog_q <- plogis(homog_draws$logit_q)
homog_min_S <- apply(homog_draws$S_prop, 1, min)
homog_max_R0 <- apply(homog_draws$R0_t, 1, max)
homog_immune_2025 <- homog_draws$immune_prop[, ncol(homog_draws$immune_prop)]
homog_cor_q_alpha <- cor(homog_draws$logit_q, homog_draws$alpha_R)
homog_sp <- rstan::get_sampler_params(homog_fit, inc_warmup = FALSE)
homog_divergences <- sum(sapply(homog_sp, function(x) sum(x[, "divergent__"])))
homog_case_ppc_rmse <- sqrt(mean((apply(homog_draws$C_pred, 2, median) - homog$stan_data$C)^2))
homog_u14_pred <- homog_draws$p_site_window[, 1]

spatial_min_S <- apply(draws$S_prop, 1, min)
spatial_max_R0 <- apply(draws$R0_t, 1, max)
spatial_case_ppc_rmse <- sqrt(mean((apply(draws$C_pred, c(2, 3), median) - b$stan_data$C)^2))

comparison <- tibble(
  metric = c("HMC status", "q (median [95% CrI])", "min S/N (any stratum/state)", "immune_2025 (statewide, median)",
             "max R0 (any stratum/state)", "cor(logit_q, alpha)", "case PPC RMSE (per obs)", "U14 fit (model median [95% CrI] vs observed)"),
  homogeneous_model = c(
    if (homog_divergences == 0) "PASS-ish (see model notes)" else sprintf("FAIL (%d divergences)", homog_divergences),
    sprintf("%.4f [%.4f, %.4f]", median(homog_q), quantile(homog_q, .025), quantile(homog_q, .975)),
    sprintf("%.4f", median(homog_min_S)),
    sprintf("%.4f", median(homog_immune_2025)),
    sprintf("%.2f", median(homog_max_R0)),
    sprintf("%.3f", homog_cor_q_alpha),
    sprintf("%.2f", homog_case_ppc_rmse),
    sprintf("%.4f [%.4f, %.4f] vs %.4f", median(homog_u14_pred), quantile(homog_u14_pred, .025), quantile(homog_u14_pred, .975), obs_prev)
  ),
  spatial_5strata_model = c(
    if (b$hmc$hmc_pass) "PASS" else sprintf("FAIL (%d divergences)", b$hmc$divergences),
    sprintf("%.4f [%.4f, %.4f]", median(q_draws <- plogis(draws$logit_q)), quantile(q_draws, .025), quantile(q_draws, .975)),
    sprintf("%.4f", median(spatial_min_S)),
    sprintf("%.4f", median(draws$U_PE_prop[, ncol(draws$U_PE_prop)])),
    sprintf("%.2f", median(spatial_max_R0)),
    sprintf("%.3f", cor(draws$logit_q, draws$alpha_global)),
    sprintf("%.2f", spatial_case_ppc_rmse),
    sprintf("%.4f [%.4f, %.4f] vs %.4f", median(p_site), quantile(p_site, .025), quantile(p_site, .975), obs_prev)
  )
)
message("\n=== Section 18: homogeneous vs spatial comparison ===")
print(as.data.frame(comparison))
write_csv(comparison, file.path(table_dir, "PE_homogeneous_vs_spatial.csv"))
message("[saved] ", file.path(table_dir, "PE_homogeneous_vs_spatial.csv"))

# ---- Comparison figure: q and min-S/N side by side -------------------------
q_compare_df <- bind_rows(tibble(model = "Homogeneous", q = homog_q), tibble(model = "Spatial (5-strata)", q = q_draws))
S_compare_df <- bind_rows(tibble(model = "Homogeneous", min_S = homog_min_S), tibble(model = "Spatial (5-strata)", min_S = spatial_min_S))
p_q <- ggplot(q_compare_df, aes(q, fill = model)) + geom_density(alpha = 0.5) +
  labs(title = "q_PE posterior: homogeneous vs spatial", x = "q", y = "Density") + theme_v4 + theme(legend.position = "top")
p_S <- ggplot(S_compare_df, aes(min_S, fill = model)) + geom_density(alpha = 0.5) +
  labs(title = "Minimum S/N posterior: homogeneous (statewide) vs spatial (any stratum)", x = "min(S/N)", y = "Density") +
  theme_v4 + theme(legend.position = "none")
ggsave(file.path(figure_dir, "PE_homogeneous_vs_spatial_q_S.png"), p_q / p_S, width = 200, height = 180, units = "mm", dpi = 300, bg = "white")
message("[saved] ", file.path(figure_dir, "PE_homogeneous_vs_spatial_q_S.png"))
